#####
# Run command - default to restart sssd.service
# ansible-playbook ./playbooks/server-service-restart.yml -i <targetServer>, --ask-become
# 
# Run command to restart specific service - for example restart autofs.service
# ansible-playbook ./playbooks/server-service-restart.yml -i <targetServer>, --extra-vars "target_service=autofs.service" --ask-become
#
# To post message to slack, export slack token to env variable then add extra-var to command line, 
# for example: --extra-vars "slack_webhook_token=$SLACK_TOKEN"
#####
---
- name: Ansible restart a service
  hosts: all
  become: true
  gather_facts: true
  vars:
    # set default service to start or change it from cli
    target_service: "sssd.service"
    slack_webhook_token: ""

  tasks:
  # restart service with service module
  - name: Restart services
    ansible.builtin.service:
      name: "{{ target_service }}"
      state: restarted
    register: result
    tags:
      - setup

  # For debuging
  - name: Print debug messages
    ansible.builtin.debug:
      var: result
      verbosity: 2
    tags:
      - setup
      
  # post message to Slack if web hook token available in env variable or AWX 's variables
  - name: Post message to Slack
    slack:
      token: "{{ slack_webhook_token }}"
      msg: "Service '{{ target_service }}' has been restarted at '{{ ansible_host }}' on '{{ ansible_date_time.iso8601 }}'"
    no_log: True
    register: slack_posted
    when: slack_webhook_token != ""
    tags:
      - setup

  # print task run to log for audit trail if we skip post message to slack
  - name: Print service restart time stamp
    ansible.builtin.debug:
      msg: 
      - "Service '{{ target_service }}' has been restarted at '{{ ansible_host }}' on '{{ ansible_date_time.iso8601 }}'"
    when: slack_posted is skipped
    tags:
      - setup
